Import tất cả các bảng vào. Sử dụng sergen để sinh code, sau đó chạy Rebuild, chạy T4, rồi chạy Build Solution một lần nữa.
Issuse: Gặp lỗi
Error TS2339 (TS) Property 'Northwind' does not exist on type 'typeof ProjectMonitoring'. ProjectMonitoring.Web